version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    target-branch: main
    schedule:
      interval: "daily"
      time: "07:00"
    labels:
      - "dependencies"
    open-pull-requests-limit: 5
    reviewers:
      - "Contrast-Security-OSS/team-xyz"
      - "Contrast-Security-OSS/team-helios"
      - "Contrast-Security-OSS/ecosystem-engineering"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: main
    schedule:
      interval: "daily"
      time: "07:00"
    labels:
      - "dependencies"
    open-pull-requests-limit: 5
    reviewers:
      - "Contrast-Security-OSS/team-xyz"
      - "Contrast-Security-OSS/team-helios"
      - "Contrast-Security-OSS/ecosystem-engineering"