language: python
python:
- '3.4'
- '3.5'
- '3.6'
- '3.7'
- '3.8'
install:
- pip install -r requirements.txt
script:
- nosetests --exclude=.*
deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: "Your encrypted token"