language: python
python:
- '3.8'
install:
- pip install -r requirements.txt
script:
- nosetests --exclude=.*
deploy:
  provider: pypi
  user: __token__
  password:
    secure: OD8SV0Mfdum2IE4eUdSkBJmnXFK7JPRZIuN3/InaUlA8krKnpqcA5IuCMeXnMUbuqzV0p3eBadzcF24AYt+uxqxIKNj9lHOlg5HR2cUzltp3PMfsbinm7iNzgHlnEvmtsijwS+PLGk/Yjy57K3qprZD2hOiQFTG17IwjKjXq/D+2PuPqEuTgLknCrvFrLeQJ9r/d1Z/EZD2dOLxwkIOE27XS30f8HG6q7BtG+rr71n1d8mVh1/yxdNHXQxMQ2wSzYMh+KzXfApbXicd2zA2S4ajQq7aZd0aQmck/UdBv1rvkLXBL7AEDChfYiNC49A7zI5PJIzwin5uDpuAorqUp7S2SfADX2Sb9YCORcqja3EbbvDfoAwAgt6qH7AfsVLKINkNLi6dT8pnY/7kthaPG1CDQXRebLykZ8FIsKa9Vlg+zSk3KjBtjzYG7Rh9dO4qO+p+wKAQljYzqh78T3MefyFUc5u4dBE9RsCRfnkz0+PxnZ2rioRxmL04hzGxpNyBO+5jQyBXi2QKJodToapyHeYx2/wxkEL9KE9V6tCKCRfiKxz8P3QF1hHX9VD9lDM5qL1iXJiN6H+MApb8qf8d36NduKpb4jahxLcKS38rzTql/AlGIPn8KAPruxxmnhoMKkPVsz+Z6ijvWwCa2GE3P6m3ohYTBoXc8+s5p/u1tmrQ=
  on:
    branch: master
env:
  global:
    secure: AZJ7S0ghjPzvH9bbO2vTXf1QQRzn5ncn7gbM1ll/O400gD93GRxinsaOKMcPo2rpw55jHLO5LjXPMS8Rh2E0nx1to3zacsOuANIeiGjGSlEjAt9u5oqGAKU+L3HTMz8mTymAXd5XpoY4A7rHQpvJRe2NWd5qOWIhtyS9HFSRfpLsdT5RZkcyV1J31XJbxaQFjvHXCtMwsnag+m4eu/O2KXm9qHnUpSAvHgbcvnSg7DHkmLdlM64JCDbTciR2OreiDrJFoqRFFn5azzCpm349YiMWK6b0EGinSpyS4hRLi5at2LmWm+EMkoT1a9N9dvL1IzyAAxMhnjuJJAYfduLF6C664T23f+P/GItFLL7KizG/1wtI/gS2AMzXXuxRpncxkX0c93E0mOdtE6dTn8p9mbSo8PTT7xAtFCiT6h4ygCSBvWvDdfPoGInITxmFQB4VCHUr7cyPo1qiYZEuwJ4zrbktGySA+iViscI76VFX4OpMoDXuW8578R2PYc2gqqqQXpgSvjhlsyWOixcjhj51X0zTZXe0NUaQISDKlMLpM9b8G4GhtbiUuG9p+R92aj4MUNMvYQE5aPCqEnfco02rN/chgprwPQSBQL34W8tPejZYROgZgzwFlwLPsobH2M6qBv/f9fbqTo2Dx9/NDcjISBT+7GPoYpHrX44tkfwQaRo=
