language: python
python:
- '3.8'
install:
- pip install -r requirements.txt
script:
- nosetests --exclude=.*
deploy:
  provider: pypi
  user: __token__
  password: $PYPI_DEPLOY_KEY
  on:
    branch: master
env:
  global:
    secure: AZJ7S0ghjPzvH9bbO2vTXf1QQRzn5ncn7gbM1ll/O400gD93GRxinsaOKMcPo2rpw55jHLO5LjXPMS8Rh2E0nx1to3zacsOuANIeiGjGSlEjAt9u5oqGAKU+L3HTMz8mTymAXd5XpoY4A7rHQpvJRe2NWd5qOWIhtyS9HFSRfpLsdT5RZkcyV1J31XJbxaQFjvHXCtMwsnag+m4eu/O2KXm9qHnUpSAvHgbcvnSg7DHkmLdlM64JCDbTciR2OreiDrJFoqRFFn5azzCpm349YiMWK6b0EGinSpyS4hRLi5at2LmWm+EMkoT1a9N9dvL1IzyAAxMhnjuJJAYfduLF6C664T23f+P/GItFLL7KizG/1wtI/gS2AMzXXuxRpncxkX0c93E0mOdtE6dTn8p9mbSo8PTT7xAtFCiT6h4ygCSBvWvDdfPoGInITxmFQB4VCHUr7cyPo1qiYZEuwJ4zrbktGySA+iViscI76VFX4OpMoDXuW8578R2PYc2gqqqQXpgSvjhlsyWOixcjhj51X0zTZXe0NUaQISDKlMLpM9b8G4GhtbiUuG9p+R92aj4MUNMvYQE5aPCqEnfco02rN/chgprwPQSBQL34W8tPejZYROgZgzwFlwLPsobH2M6qBv/f9fbqTo2Dx9/NDcjISBT+7GPoYpHrX44tkfwQaRo=
